"""change log property to file_path

Revision ID: 1723922074
Revises: 
Create Date: 2024-08-17 21:14:34.515414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1723922074'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('file_path', sa.String(), nullable=False))
    op.drop_column('log', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('value', sa.VARCHAR(), nullable=False))
    op.drop_column('log', 'file_path')
    # ### end Alembic commands ###
