"""add is_ready

Revision ID: 1724100886
Revises: 1723922205
Create Date: 2024-08-19 22:54:46.389005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1724100886'
down_revision: Union[str, None] = '1723922205'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translucent_log', sa.Column('is_ready', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translucent_log', 'is_ready')
    # ### end Alembic commands ###
