/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutEventLogsIndexImport } from './routes/_layout/event-logs/index'
import { Route as LayoutEventLogsEventLogIdIndexImport } from './routes/_layout/event-logs/$eventLogId/index'
import { Route as LayoutEventLogsEventLogIdTransformerIndexImport } from './routes/_layout/event-logs/$eventLogId/transformer/index'
import { Route as LayoutEventLogsEventLogIdPrefixAutomatonIndexImport } from './routes/_layout/event-logs/$eventLogId/prefix-automaton/index'
import { Route as LayoutEventLogsEventLogIdPetriNetIndexImport } from './routes/_layout/event-logs/$eventLogId/petri-net/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutEventLogsIndexRoute = LayoutEventLogsIndexImport.update({
  path: '/event-logs/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutEventLogsEventLogIdIndexRoute =
  LayoutEventLogsEventLogIdIndexImport.update({
    path: '/event-logs/$eventLogId/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutEventLogsEventLogIdTransformerIndexRoute =
  LayoutEventLogsEventLogIdTransformerIndexImport.update({
    path: '/event-logs/$eventLogId/transformer/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutEventLogsEventLogIdPrefixAutomatonIndexRoute =
  LayoutEventLogsEventLogIdPrefixAutomatonIndexImport.update({
    path: '/event-logs/$eventLogId/prefix-automaton/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutEventLogsEventLogIdPetriNetIndexRoute =
  LayoutEventLogsEventLogIdPetriNetIndexImport.update({
    path: '/event-logs/$eventLogId/petri-net/',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/event-logs/': {
      id: '/_layout/event-logs/'
      path: '/event-logs'
      fullPath: '/event-logs'
      preLoaderRoute: typeof LayoutEventLogsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/event-logs/$eventLogId/': {
      id: '/_layout/event-logs/$eventLogId/'
      path: '/event-logs/$eventLogId'
      fullPath: '/event-logs/$eventLogId'
      preLoaderRoute: typeof LayoutEventLogsEventLogIdIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/event-logs/$eventLogId/petri-net/': {
      id: '/_layout/event-logs/$eventLogId/petri-net/'
      path: '/event-logs/$eventLogId/petri-net'
      fullPath: '/event-logs/$eventLogId/petri-net'
      preLoaderRoute: typeof LayoutEventLogsEventLogIdPetriNetIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/event-logs/$eventLogId/prefix-automaton/': {
      id: '/_layout/event-logs/$eventLogId/prefix-automaton/'
      path: '/event-logs/$eventLogId/prefix-automaton'
      fullPath: '/event-logs/$eventLogId/prefix-automaton'
      preLoaderRoute: typeof LayoutEventLogsEventLogIdPrefixAutomatonIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/event-logs/$eventLogId/transformer/': {
      id: '/_layout/event-logs/$eventLogId/transformer/'
      path: '/event-logs/$eventLogId/transformer'
      fullPath: '/event-logs/$eventLogId/transformer'
      preLoaderRoute: typeof LayoutEventLogsEventLogIdTransformerIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LayoutRoute: LayoutRoute.addChildren({
    LayoutEventLogsIndexRoute,
    LayoutEventLogsEventLogIdIndexRoute,
    LayoutEventLogsEventLogIdPetriNetIndexRoute,
    LayoutEventLogsEventLogIdPrefixAutomatonIndexRoute,
    LayoutEventLogsEventLogIdTransformerIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/event-logs/",
        "/_layout/event-logs/$eventLogId/",
        "/_layout/event-logs/$eventLogId/petri-net/",
        "/_layout/event-logs/$eventLogId/prefix-automaton/",
        "/_layout/event-logs/$eventLogId/transformer/"
      ]
    },
    "/_layout/event-logs/": {
      "filePath": "_layout/event-logs/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/event-logs/$eventLogId/": {
      "filePath": "_layout/event-logs/$eventLogId/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/event-logs/$eventLogId/petri-net/": {
      "filePath": "_layout/event-logs/$eventLogId/petri-net/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/event-logs/$eventLogId/prefix-automaton/": {
      "filePath": "_layout/event-logs/$eventLogId/prefix-automaton/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/event-logs/$eventLogId/transformer/": {
      "filePath": "_layout/event-logs/$eventLogId/transformer/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
