/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutEventLogsIndexImport } from './routes/_layout/event-logs/index'
import { Route as LayoutEventLogsEventLogIdIndexImport } from './routes/_layout/event-logs/$eventLogId/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutEventLogsIndexRoute = LayoutEventLogsIndexImport.update({
  path: '/event-logs/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutEventLogsEventLogIdIndexRoute =
  LayoutEventLogsEventLogIdIndexImport.update({
    path: '/event-logs/$eventLogId/',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/event-logs/': {
      id: '/_layout/event-logs/'
      path: '/event-logs'
      fullPath: '/event-logs'
      preLoaderRoute: typeof LayoutEventLogsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/event-logs/$eventLogId/': {
      id: '/_layout/event-logs/$eventLogId/'
      path: '/event-logs/$eventLogId'
      fullPath: '/event-logs/$eventLogId'
      preLoaderRoute: typeof LayoutEventLogsEventLogIdIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LayoutRoute: LayoutRoute.addChildren({
    LayoutEventLogsIndexRoute,
    LayoutEventLogsEventLogIdIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/event-logs/",
        "/_layout/event-logs/$eventLogId/"
      ]
    },
    "/_layout/event-logs/": {
      "filePath": "_layout/event-logs/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/event-logs/$eventLogId/": {
      "filePath": "_layout/event-logs/$eventLogId/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
